### ISSUE TITLE
issues about gatk when running SeqMule

### ISSUE THREAD

**Issue by gangcai** [WGLab/SeqMule#169]
Hi Yunfei,
   Here is an error I met during running SeqMule.  
 The SeqMule command is:
seqmule pipeline -a r1.fastq.gz -b r2.fastq.gz -advanced ./predefined_config/snap_freebayes.config -quick -t 6 -g -prefix wgseg

The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836

Following is the error message:
NOTICE: Counting non-empty lines in /tmp/937066.1.all.q/142865129141.234536126_nofiltered.vcf
NOTICE: 0 records removed because of being filtered.
##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:90)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
	... 4 more
##### ERROR ------------------------------------------------------------------------------------------
ERROR: Failed to split VCF by sample
NOTICE: Cleaning...

----------ERROR----------
[ => SeqMule Execution Status: step 13 FAILED at Tue Feb 13 20:15:24 EST 2018, Merge split VCF]
ERROR: command failed
~/lab//packages/SeqMule/bin/secondary/../../bin/secondary/worker ~/lab//projects/WGS_Analysis/run_SeqMule/WGS/seqmule.02122018.122783.logs 13 "~/lab//packages/SeqMule/bin/secondary/../../bin/seqmule stats -tmpdir /tmp/937066.1.all.q -ref ~/lab//packages/SeqMule/bin/secondary/../../database/human_g1k_v37.fasta -jmem 1750m -jexe java  -t 2 -u-vcf wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.0_freebayes.vcf,wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.1_freebayes.vcf,wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.2_freebayes.vcf,wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.3_freebayes.vcf,wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.4_freebayes.vcf,wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.5_freebayes.vcf -p wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.0_freebayes && mv -f wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.0_freebayes_union.vcf wgseg_result/wgseg.0_snap.sort.rmdup.readfiltered.0_freebayes.vcf"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After fixing the problem, please execute 'cd ~/lab//projects/WGS_Analysis/run_SeqMule/WGS' and 'seqmule run wgseg.script' to resume analysis.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yunfeiguo** [comment]
Hi 

Could you post the first few (say 10) variants plus the header lines (starting with #) in the vcf (/tmp/937066.1.all.q/142865129141.234536126_nofiltered.vcf)? Thanks.

**Comment by gangcai** [comment]
This temporary file had been deleted by the system. I will resume to run wgseg.config and hope to repeat the error.

**Comment by gangcai** [comment]
Here is the error message to run:
seqmule run wgseg.script

It seems that to resume to run SeqMule, it still needs those temporary files generated from last step.

Current version: 1.2.6
[ => SeqMule Execution Status: step 8 is finished at Fri Feb 16 16:01:12 EST 2018, freebayes variant calling]

[ => SeqMule Execution Status: step 9 is finished at Fri Feb 16 16:01:12 EST 2018, freebayes variant calling]

[ => SeqMule Execution Status: step 10 is finished at Fri Feb 16 16:01:12 EST 2018, freebayes variant calling]

[ => SeqMule Execution Status: step 11 is finished at Fri Feb 16 16:01:12 EST 2018, freebayes variant calling]

[ => SeqMule Execution Status: step 12 is finished at Fri Feb 16 16:01:12 EST 2018, freebayes variant calling]

Check for upgrade ...
NOTICE: This is the latest version!
sh: /tmp/937066.1.all.q/190774148494.804902188_nofiltered.vcf: No such file or directory
ERROR: Failed to extract variants that passed filtering or have no filter.

**Comment by yunfeiguo** [comment]
Could you rerun from the step right before all freebayes steps?
