### ISSUE TITLE
java.lang.IllegalArgumentException:#gatk#variantcalling

### ISSUE THREAD

**Issue by ashaneev** [WGLab/SeqMule#174]
I've tried with the following command for variant calling through gatk. But it didn't create any out file. 

> **./gatk VariantFiltration -R /home/Documents/Tools_NGS/VariantCall/genome_assembly.fa  -V /media/TOSHIBAEXT/Variant_Calling/variantData/snps_300bp.vcf.gz  -O snp_output.vcf.gz  --filter-expression "AB < 0.2 || MQ0 > 50"** 

Using GATK jar /home/Documents/Tools_NGS/gatk-4.0.6.0/gatk-package-4.0.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/Documents/Tools_NGS/gatk-4.0.6.0/gatk-package-4.0.6.0-local.jar VariantFiltration -R /home/Documents/Tools_NGS/VariantCall/genome_assembly.fa -V /media/TOSHIBAEXT/Variant_Calling/variantData/snps_300bp.vcf.gz -O snp_output.vcf.gz --filter-expression AB < 0.2 || MQ0 > 50
12:29:04.413 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/Documents/Tools_NGS/gatk-4.0.6.0/gatk-package-4.0.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
12:29:08.256 INFO  VariantFiltration - ------------------------------------------------------------
12:29:08.257 INFO  VariantFiltration - The Genome Analysis Toolkit (GATK) v4.0.6.0
12:29:08.257 INFO  VariantFiltration - For support and documentation go to https://software.broadinstitute.org/gatk/
12:29:08.257 INFO  VariantFiltration - Executing as home@home-Lenovo-H30-50 on Linux v4.4.0-31-generic amd64
12:29:08.257 INFO  VariantFiltration - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_171-b11
12:29:08.257 INFO  VariantFiltration - Start Date/Time: 26 September, 2018 12:29:04 PM IST
12:29:08.257 INFO  VariantFiltration - ------------------------------------------------------------
12:29:08.257 INFO  VariantFiltration - ------------------------------------------------------------
12:29:08.258 INFO  VariantFiltration - HTSJDK Version: 2.16.0
12:29:08.258 INFO  VariantFiltration - Picard Version: 2.18.7
12:29:08.258 INFO  VariantFiltration - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:29:08.258 INFO  VariantFiltration - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:29:08.258 INFO  VariantFiltration - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:29:08.258 INFO  VariantFiltration - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:29:08.258 INFO  VariantFiltration - Deflater: IntelDeflater
12:29:08.258 INFO  VariantFiltration - Inflater: IntelInflater
12:29:08.258 INFO  VariantFiltration - GCS max retries/reopens: 20
12:29:08.258 INFO  VariantFiltration - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
12:29:08.258 INFO  VariantFiltration - Initializing engine
12:29:10.301 INFO  FeatureManager - Using codec VCFCodec to read file file:///media/TOSHIBAEXT/Variant_Calling/variantData/snps_300bp.vcf.gz
12:29:11.469 INFO  VariantFiltration - Done initializing engine
12:29:11.471 INFO  VariantFiltration - Shutting down engine
[26 September, 2018 12:29:11 PM IST] org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration done. Elapsed time: 0.12 minutes.
Runtime.totalMemory()=576192512
java.lang.IllegalArgumentException: Inconsistent number of provided filter names and expressions: names=[] exps=[AB < 0.2 || MQ0 > 50]
	at htsjdk.variant.variantcontext.VariantContextUtils.initializeMatchExps(VariantContextUtils.java:238)
	at htsjdk.variant.variantcontext.VariantContextUtils.initializeMatchExps(VariantContextUtils.java:259)
	at org.broadinstitute.hellbender.tools.walkers.filters.VariantFiltration.onTraversalStart(VariantFiltration.java:284)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:982)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:135)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:180)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:199)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

Please help me to find a solution for this..thankyou.

**Comment by yunfeiguo** [comment]
gatk complained

java.lang.IllegalArgumentException: Inconsistent number of provided filter
names and expressions: names=[] exps=[AB < 0.2 || MQ0 > 50]

please refer to
https://gatkforums.broadinstitute.org/gatk/discussion/4737/error-during-filtering-variant-step

Thanks.
