### ISSUE TITLE
ava.lang.IllegalArgumentException: Inconsistent number of provided filter names and expressions: names=[] exps=[AB < 0.2 || MQ0 > 50]

### ISSUE THREAD

**Issue by elbakrifz** [WGLab/SeqMule#181]
I have tried with the following CML : java -Xmx4G -jar /Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836\ 4/GenomeAnalysisTK.jar \ -T VariantFiltration \ -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta \ -V /Users/mac/Desktop/NGS-/59variants.vcf \ -o /Users/mac/Desktop/NGS-/59variants.vcf \ --filterExpression "AB < 0.2 || MQ0 > 50" 
 I get : 
INFO  19:41:16,071 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50 
INFO  19:41:16,071 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
INFO  19:41:16,072 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk 
INFO  19:41:16,073 HelpFormatter - [Tue Aug 25 19:41:16 WEST 2020] Executing on Mac OS X 10.15.6 x86_64 
INFO  19:41:16,073 HelpFormatter - Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 
INFO  19:41:16,080 HelpFormatter - Program Args:  -T GenotypeGVCFs  -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta  -V /Users/mac/Desktop/NGS-/42variants.g.vcf  -o /Users/mac/Desktop/NGS-/42variants.vcf 
INFO  19:41:16,243 HelpFormatter - Executing as mac@MacBook-Air-de-mac.local on Mac OS X 10.15.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17. 
INFO  19:41:16,244 HelpFormatter - Date/Time: 2020/08/25 19:41:16 
INFO  19:41:16,245 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  19:41:16,245 HelpFormatter - ---------------------------------------------------------------------------------- 
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836%204/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
INFO  19:41:17,138 GenomeAnalysisEngine - Deflater: IntelDeflater 
INFO  19:41:17,138 GenomeAnalysisEngine - Inflater: IntelInflater 
INFO  19:41:17,139 GenomeAnalysisEngine - Strictness is SILENT 
INFO  19:41:17,240 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000 
INFO  19:41:17,417 GenomeAnalysisEngine - Preparing for traversal 
INFO  19:41:17,419 GenomeAnalysisEngine - Done preparing for traversal 
INFO  19:41:17,419 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING] 
INFO  19:41:17,420 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining 
INFO  19:41:17,420 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime 
WARN  19:41:17,540 StrandBiasTest - StrandBiasBySample annotation exists in input VCF header. Attempting to use StrandBiasBySample values to calculate strand bias annotation values. If no sample has the SB genotype annotation, annotation may still fail. 
WARN  19:41:17,540 InbreedingCoeff - Annotation will not be calculated. InbreedingCoeff requires at least 10 unrelated samples. 
WARN  19:41:17,541 StrandBiasTest - StrandBiasBySample annotation exists in input VCF header. Attempting to use StrandBiasBySample values to calculate strand bias annotation values. If no sample has the SB genotype annotation, annotation may still fail. 
INFO  19:41:17,542 GenotypeGVCFs - Notice that the -ploidy parameter is ignored in GenotypeGVCFs tool as this is automatically determined by the input variant files 
WARN  19:41:17,699 HaplotypeScore - Annotation will not be calculated, must be called from UnifiedGenotyper, not GenotypeGVCFs 
INFO  19:41:47,428 ProgressMeter - LmjF18_01_20050601_V5.2:104301   7741089.0    30.0 s       3.0 s       23.9%     2.1 m      95.0 s 
INFO  19:42:17,437 ProgressMeter - LmjF35_01_20050601_V5.2:415001   2.1195519E7    60.0 s       2.0 s       65.8%    91.0 s      31.0 s 
INFO  19:42:40,369 ProgressMeter -            done   3.2855403E7    82.0 s       2.0 s      100.0%    82.0 s       0.0 s 
INFO  19:42:40,370 ProgressMeter - Total runtime 82.95 secs, 1.38 min, 0.02 hours 
------------------------------------------------------------------------------------------
Done. There were 4 WARN messages, the first 4 are repeated below.
WARN  19:41:17,540 StrandBiasTest - StrandBiasBySample annotation exists in input VCF header. Attempting to use StrandBiasBySample values to calculate strand bias annotation values. If no sample has the SB genotype annotation, annotation may still fail. 
WARN  19:41:17,540 InbreedingCoeff - Annotation will not be calculated. InbreedingCoeff requires at least 10 unrelated samples. 
WARN  19:41:17,541 StrandBiasTest - StrandBiasBySample annotation exists in input VCF header. Attempting to use StrandBiasBySample values to calculate strand bias annotation values. If no sample has the SB genotype annotation, annotation may still fail. 
WARN  19:41:17,699 HaplotypeScore - Annotation will not be calculated, must be called from UnifiedGenotyper, not GenotypeGVCFs 
------------------------------------------------------------------------------------------
(base) MacBook-Air-de-mac:~ mac$ java -Xmx4G -jar /Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836\ 4/GenomeAnalysisTK.jar \ -T VariantFiltration \ -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta \ -V /Users/mac/Desktop/NGS-/59variants.vcf \ -o /Users/mac/Desktop/NGS-/59variants.vcf \ --filterExpression "AB < 0.2 || MQ > 50" 
INFO  11:26:16,702 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  11:26:16,710 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50 
INFO  11:26:16,710 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
INFO  11:26:16,711 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk 
INFO  11:26:16,711 HelpFormatter - [Wed Aug 26 11:26:16 WEST 2020] Executing on Mac OS X 10.15.6 x86_64 
INFO  11:26:16,712 HelpFormatter - Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 
INFO  11:26:16,716 HelpFormatter - Program Args:  -T VariantFiltration  -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta  -V /Users/mac/Desktop/NGS-/59variants.vcf  -o /Users/mac/Desktop/NGS-/59variants.vcf  --filterExpression AB < 0.2 || MQ > 50 
INFO  11:26:16,926 HelpFormatter - Executing as mac@MacBook-Air-de-mac.local on Mac OS X 10.15.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17. 
INFO  11:26:16,927 HelpFormatter - Date/Time: 2020/08/26 11:26:16 
INFO  11:26:16,927 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  11:26:16,928 HelpFormatter - ---------------------------------------------------------------------------------- 
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836%204/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
INFO  11:26:19,995 GenomeAnalysisEngine - Deflater: IntelDeflater 
INFO  11:26:19,996 GenomeAnalysisEngine - Inflater: IntelInflater 
INFO  11:26:19,996 GenomeAnalysisEngine - Strictness is SILENT 
INFO  11:26:20,255 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000 
INFO  11:26:20,788 GenomeAnalysisEngine - Preparing for traversal 
INFO  11:26:20,789 GenomeAnalysisEngine - Done preparing for traversal 
INFO  11:26:20,789 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING] 
INFO  11:26:20,790 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining 
INFO  11:26:20,790 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime 
##### ERROR stack trace 
java.lang.IllegalArgumentException: Inconsistent number of provided filter names and expressions: names=[] exps=[AB < 0.2 || MQ > 50]
	at htsjdk.variant.variantcontext.VariantContextUtils.initializeMatchExps(VariantContextUtils.java:238)
	at htsjdk.variant.variantcontext.VariantContextUtils.initializeMatchExps(VariantContextUtils.java:259)
	at org.broadinstitute.gatk.tools.walkers.filters.VariantFiltration.initialize(VariantFiltration.java:251)
	at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:83)
	at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:323)
	at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:123)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:256)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:158)
	at org.broadinstitute.gatk.engine.CommandLineGATK.main(CommandLineGATK.java:108)
##### ERROR ------------------------------------------------------------------------------------------
(base) MacBook-Air-de-mac:~ mac$ java -Xmx4G -jar /Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836\ 4/GenomeAnalysisTK.jar \ -T VariantFiltration \ -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta \ -V /Users/mac/Desktop/NGS-/59variants.vcf \ -o /Users/mac/Desktop/NGS-/59variants.vcf \ --filterExpression "AB < 0.2 || MQ0 > 50" 
INFO  11:31:49,414 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  11:31:49,416 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50 
INFO  11:31:49,416 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
INFO  11:31:49,417 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk 
INFO  11:31:49,417 HelpFormatter - [Wed Aug 26 11:31:49 WEST 2020] Executing on Mac OS X 10.15.6 x86_64 
INFO  11:31:49,417 HelpFormatter - Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 
INFO  11:31:49,421 HelpFormatter - Program Args:  -T VariantFiltration  -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta  -V /Users/mac/Desktop/NGS-/59variants.vcf  -o /Users/mac/Desktop/NGS-/59variants.vcf  --filterExpression AB < 0.2 || MQ0 > 50 
INFO  11:31:49,598 HelpFormatter - Executing as mac@MacBook-Air-de-mac.local on Mac OS X 10.15.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17. 
INFO  11:31:49,599 HelpFormatter - Date/Time: 2020/08/26 11:31:49 
INFO  11:31:49,599 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  11:31:49,600 HelpFormatter - ---------------------------------------------------------------------------------- 
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836%204/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
INFO  11:31:50,440 GenomeAnalysisEngine - Deflater: IntelDeflater 
INFO  11:31:50,440 GenomeAnalysisEngine - Inflater: IntelInflater 
INFO  11:31:50,441 GenomeAnalysisEngine - Strictness is SILENT 
INFO  11:31:50,541 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000 
INFO  11:31:50,699 GenomeAnalysisEngine - Preparing for traversal 
INFO  11:31:50,701 GenomeAnalysisEngine - Done preparing for traversal 
INFO  11:31:50,702 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING] 
INFO  11:31:50,702 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining 
INFO  11:31:50,702 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime 
##### ERROR stack trace 
java.lang.IllegalArgumentException: Inconsistent number of provided filter names and expressions: names=[] exps=[AB < 0.2 || MQ0 > 50]
	at htsjdk.variant.variantcontext.VariantContextUtils.initializeMatchExps(VariantContextUtils.java:238)
	at htsjdk.variant.variantcontext.VariantContextUtils.initializeMatchExps(VariantContextUtils.java:259)
	at org.broadinstitute.gatk.tools.walkers.filters.VariantFiltration.initialize(VariantFiltration.java:251)
	at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:83)
	at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:323)
	at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:123)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:256)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:158)
	at org.broadinstitute.gatk.engine.CommandLineGATK.main(CommandLineGATK.java:108)
##### ERROR ------------------------------------------------------------------------------------------  
how should I fix it ?!

**Comment by yunfeiguo** [comment]
Hi @elbakrifz this is more of GATK problem than a problem of SeqMule, please refer to https://cc.bingj.com/cache.aspx?q=Inconsistent+number+of+provided+filter+names+and+expressions&d=4818888926822978&mkt=en-US&setlang=en-US&w=4LBNNkST4HePYIU1e4fZ_9kSrrvxE4yZ for some info.
