### ISSUE TITLE
Run example  fastq files with error

### ISSUE THREAD

**Issue by DecodeGenome** [WGLab/SeqMule#187]
Hi Yunfei,

I newly installed SeqMule (SeqMule-master) on CentOS, seqmule download the database, and ran the example command with example fastq files, I got error, how to fix it? Thanks for your help. WEI
############################################################################################
java -Xmx1750m  -Djava.io.tmpdir=/scratch/wwu888 -jar /wynton/group/bivona/Analytic_tools/SeqMule-master/exe/gatklite/GenomeAnalysisTKLite.jar  -T IndelRealigner -I example_result/example.0_bwamem.sort.rmdup.readfiltered.bam -R /wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../database/human_g1k_v37.fasta -targetIntervals /scratch/wwu888/8505.50003740059.tmp.intervals --out example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.bam -maxInMemory 200000 -L /wynton/group/bivona/Analytic_tools/SeqMule-master/misc/hg19_exonPlus5bp_UCSCrefGene.bed -rf NotPrimaryAlignment -l ERROR 
rm -rf /scratch/wwu888/8505.50003740059.tmp.intervals
/wynton/group/bivona/Analytic_tools/SeqMule-master/exe/samtools/samtools index example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.bam at /wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../bin/secondary/runGATKLITEREALN line 78.
##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:90)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
	... 4 more
##### ERROR ------------------------------------------------------------------------------------------

----------ERROR----------
[ => SeqMule Execution Status: step 7 FAILED at Tue May  3 20:13:10 PDT 2022, gatklite realn]
ERROR: command failed
/wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../bin/secondary/worker /wynton/group/bivona/Data/Seqmule_Test_fq_May3_2022/seqmule.05032022.10358.logs 7 "/wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../bin/secondary/runGATKLITEREALN -advanced example.config -n 6 -ref /wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../database/human_g1k_v37.fasta -java java -jmem 1750m -gatk /wynton/group/bivona/Analytic_tools/SeqMule-master/exe/gatklite/GenomeAnalysisTKLite.jar -threads 4 -gatk-nt 2 -tmpdir /scratch/wwu888  -bed /wynton/group/bivona/Analytic_tools/SeqMule-master/misc/hg19_exonPlus5bp_UCSCrefGene.bed -goldindel /wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../database/Mills_and_1000G_gold_standard.indels.b37.vcf  -dbsnp /wynton/group/bivona/Analytic_tools/SeqMule-master/bin/secondary/../../database/dbsnp_hg19_138.vcf  -samtools /wynton/group/bivona/Analytic_tools/SeqMule-master/exe/samtools/samtools  -pl ILLUMINA  -bam example_result/example.0_bwamem.sort.rmdup.readfiltered.bam -out example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.bam "
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After fixing the problem, please execute 'cd /wynton/group/bivona/Data/Seqmule_Test_fq_May3_2022' and 'seqmule run example.script' to resume analysis.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yunfeiguo** [comment]
Hi @DecodeGenome what's your java version (`java -version`)? This issue might be caused by the main problem as in #186

**Comment by DecodeGenome** [comment]
Hi Yunfei: thanks for your response, below is the java version on HPC dev node:
Thanks
Wei
###############
(base) [wwu888@dev3 ~]$ java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

**Comment by yunfeiguo** [comment]
Can you try Oracle jdk8? The NullPointer exception is clueless to me otherwise. You can also try dockerized seqmule (https://hub.docker.com/layers/seqmule/genomicslab/seqmule/latest/images/sha256-09d8c5458f956cf6e7213a90b14657e0fea68d84e6a812f4100199f99cf5272f?context=explore).
________________________________
发件人: DecodeGenome ***@***.***>
发送时间: Wednesday, May 4, 2022 9:34:51 PM
收件人: WGLab/SeqMule ***@***.***>
抄送: Yunfei Guo ***@***.***>; Comment ***@***.***>
主题: Re: [WGLab/SeqMule] Run example fastq files with error (Issue #187)


Hi Yunfei: thanks for your response, below is the java version on HPC dev node:
Thanks
Wei
###############
(base) ***@***.*** ~]$ java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

―

**Comment by DecodeGenome** [comment]
Thank you YUNFEI, I may try to use dockerized seqmule as you suggest.

**Comment by DecodeGenome** [comment]
Hi Yunfei, I have pulled genomiclab/seqmule image, I tried to run "docker run -it genomiclab/seqmule pipeline " it does not work. since I am not familiar too much with docker, do you have detailed instructions to use docker for seqmule? 

Thanks,

Wei

**Comment by yunfeiguo** [comment]
Hi @DecodeGenome please try the following command as dockerized quick start in tutorial (https://doc-openbio.readthedocs.io/projects/seqmule/en/latest/Tutorials/Quick%20start/)
```
docker run -v $(pwd):/input -v $(pwd)/output:/opt/app-root/src -it genomicslab/seqmule /opt/SeqMule/bin/seqmule pipeline -a /root/normal_R1.fastq.gz -b /root/normal_R2.fastq.gz -prefix example -N 2 -capture default -threads 4 -e
```
assuming you have `normal_R1.fastq.gz` and `normal_R2.fastq.gz` in your current working directory plus an `output` folder. The `/opt/app-root/src` path is the default working directory after logging into docker container and is used for storing output files.
